---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgBJsVH0BatUTmYniKr3W/LtbRFBK/e0wDR0FA3KUAUfcvsCeAJTcuaukAZckxN/vDvnXwT3ZtLWiRuBkec59wB6L4C/Cq5Rv9MBwvu4WDJON0HmG7oWS27OOlZMpzQpeMZXsUuzb5YrnVtM8ZnPhBNvXlV8Ts7tpa9BFsJgZEeQA2P1uJy85oPFZO6OUn9IYmc1OJvN4FE+gnfM8FbT/FQzLx3v7jaKQsHOydzC2/7afA5QN9MTP7EoRilR+YR6OAxMN2/AdHPSg5yeGpK+AIhj3SAgZ7AHOdY/Q02/AfLGxvKFEga3+Ou5nj3yoK4nNuX/QVGdl4rvhNsjfPum2nKr3cejXE+VocnOLD8otnKfLAkDHLD9b8We4NQ6WUi3H+HiHLUspArhysOowDRbJ9mYXNbolumJB9jDZ+XCU+D37UesNR2RlMki3vhRx5ATQb2hlrwyZCCBUSBi+hOaahVPvEe66shrTR/qvRYiTIUEpK1Mmdwy9gkwzhtpKjSuMDFAuKnvs9kGr/MlMRY9TyTxJXdhg0QfXhAl1Q75A5ghA0h8qj+kmrSZ8VfuRyVMRKLeTo4bEcUlDc+f7XqDItMpeMI5itJmyd/A6Bq6D2xRakZ5xAnx2NYaeJjza4bii/QbtWGoqTyEfH4RwQFH+5kji8lF38iDHvAHHp+O8TH3GVP5GZ3+6/mcZQCn+Cudo9rpR6Aiu4+3OcKwdiHT9M5Dmaymb/DqhLdU9ij3YR4E1MGu57++mUS5kMWjB5haaqb8Eqf9e2hBj7RE68Re24MFY24BiXapis8JEXOcX92IVAmqaaXKbwkA4x5J8eDQtcstjUIWnEKUmYp0VSvq1Wg6u4wS2Zxx9sZxTj7nEZeljTKIeLjqUwfb1jNbpwip+x1u7oH+g56eYzWUdoI0E0slA3wdJTnKlp9BXeGpBvTBPOlzHomNLunM0V11NP1WQEo9knlishXLu/yiLj4Jd4Yr0H+lbCZt1qXO5NOqSWo85aWINH/7h/Mtzwxf
  template:
    metadata:
      name: alertmanager-secret
      namespace: monitoring
    type: Opaque
