---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secret
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgBBf93wlviP5wyMo6Y+apfdMaUH/CdKe9pqyTMO6YUREP2Y9GPb7DXbLeVRJ2n20/JURU6AdvL7EiHZqHsk3BceEmFSEX6ri+N/0DCFxuxDiRFJs6/62Mw0MDv6j2kD2VaC8nEGDEA17xenrCKhSd70y9P7rU7aSVRjYlUjEo+l8ry95sX8Y38f2Y+U025rME2TfoQFviHdYNcpYA/9fGL1rGQIVA1Jlap/YXavgW3A95u3MMfmOOwsDcjjdcZ3m0SNDf/m885oiq5TM+oY5QySE4IidaouibhZgSVt5DAoNA5hghjCpOiWjUeF+nU/9C0VuKJoCX+eNv1AvfbiZ7v8xYapr55tn/N90hc3fmYnf6fWSJM9F07QfA0vtX/nuYE5fXcHWpn1TtuEQCn2sxfzdv2vD6nkQTxxf0MwbtmOk7bvHb8yrwBO5l7BXTqCKvYM6fp5G+B5b65p1NBhqC/5P3DjuvrA1Ss63XpGZxGyUyMDBrfnZIVgZqkthg6FQARbGdbIZX5Z4jvPxySFIO35+eTqIHFWy31Z5XPpF3Jjwv2891py2CpjX+VLyOpQM+HSAVqfhmq9A/guS0e9P6vaOH7vhb6E/GJSyQhUcD0pEnXyHsDgVpo1fph/mm/Pj8Kx+j6LA+jeuxjgrD+GBUTNSKaEDfOc/CNLfzzOGf1V3C4ZCU4cdp30hil/+4yRBVK1mMD31csCqhF1s/XR8Ny2PjbxHfvEQyJugTcVB2hLiHBqzoOrQVAdJgyinIk5kiuibs0qVuTe3LakeqABKcvvHI579FA4XKg1P0cxOUNK/wzEDmcWpGCF5ycgMS4LH/SMFHqTW+xKXbw0x146PbCRdt6Und3WQDJncdYltzal+ZFv2qPtAvvq/Fp+HF/PIssNM7pZQNEjIATDHCFeDn7ebxbeUi0wDUtow3l7lWe7GjTE3nNIOemIKTAFXCQteUVquW5oLkBvWr0mpxZq/in9OO2jTT0s3CbX0WA0Qr9wQJ0XNp6woDsj4owasz1BaYtP8IUBuoM=
  template:
    metadata:
      name: alertmanager-secret
      namespace: monitoring
    type: Opaque
